name: Publish to JSR
on:
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install

      - name: Publish package
        run: npx jsr publish
